name: Playwright Framework Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  playwright:
    name: 'Playwright Framework Node.js CI'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --user 1001
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies (clean)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # (Opcional) Validar build isoladamente para falhar mais cedo
      - name: Build
        run: npm run build

      - name: Run Playwright tests
        run: npx playwright test --workers=3 --reporter=html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 7
