name: Playwright Framework Node.js CI
on:
  pull_request:
    branches:  master
jobs:
  playwright:
    name: 'Playwright Framework Node.js CI'
    runs-on: ubuntu-latest
    container:
      image: "mcr.microsoft.com/playwright:v1.55.0-jammy"
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run homePage tests
        run: npx playwright test workers=3